debug: true
server:
  port: 8090

ribbon:
  eureka:
    enabled: false

zuul:
  routes:
    acme:
      url: http://localhost:8080

spring:
  application: zuul_api_gateway
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 9ae72ae47d871960b1e6
            clientSecret: 844f0ec6bedf75610b4fef42bb9d275d158dd9d7
